AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM HTTP API with Lambda functions

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    CodeUri: src/

Resources:
  # Single API Gateway that both Lambda functions will use
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowHeaders:
          - 'Content-Type'
          - 'Authorization'
          - 'Cookie'
        AllowOrigins:
          - 'http://localhost:3000'
          - 'http://localhost:5173'
        AllowCredentials: true

  # First Lambda function for /auth
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/auth_handler.lambda_handler
      Events:
        AuthEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi  # References the same API Gateway
            Path: /auth
            Method: GET

  # Second Lambda function for /validate
  ValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/validate_handler.lambda_handler
      Events:
        ValidateEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi  # References the same API Gateway
            Path: /validate
            Method: GET

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
